// Code generated by BobGen sql v0.34.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

type Factory struct {
	baseWeatherMods WeatherModSlice
}

func New() *Factory {
	return &Factory{}
}

func (f *Factory) NewWeather(mods ...WeatherMod) *WeatherTemplate {
	o := &WeatherTemplate{f: f}

	if f != nil {
		f.baseWeatherMods.Apply(o)
	}

	WeatherModSlice(mods).Apply(o)

	return o
}

func (f *Factory) ClearBaseWeatherMods() {
	f.baseWeatherMods = nil
}

func (f *Factory) AddBaseWeatherMod(mods ...WeatherMod) {
	f.baseWeatherMods = append(f.baseWeatherMods, mods...)
}
