on:
  pull_request:
  push:

jobs:
  test:
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Checkout"
        uses: "https://github.com/actions/checkout@v4.2.2"
        with:
          fetch-depth: 1

      - name: "Set up Go"
        uses: "https://github.com/actions/setup-go@v5.5.0"
        with:
          go-version: "1.24.3"

      - name: "Run tests"
        run: "go test ./..."
