// Code generated by BobGen sql v0.34.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package bobgen_gen

import "github.com/stephenafamo/bob"

// Make sure the type Weather runs hooks after queries
var _ bob.HookableType = &Weather{}
