// Code generated by BobGen sql v0.34.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package bob_gen

import "github.com/stephenafamo/bob"

// Make sure the type User runs hooks after queries
var _ bob.HookableType = &User{}
